pipelines:
  branches:
    main:
      - step:
          name: Build and test the app
          image: node:latest
          script:
            - npm install
            - npm run test
            - npm run build